apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: userservices
    tier: backend
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservices
spec:
  selector:
    matchLabels:
      app: userservices
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: userservices
        tier: backend
        track: stable
    spec:
      containers:
      - image: userservices
        imagePullPolicy: Never
        name: userservices
        ports:
        - containerPort: 5001
          protocol: TCP
      restartPolicy: Always