#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 9001

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["UserBlazor.csproj", ""]
RUN dotnet restore "./UserBlazor.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "UserBlazor.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "UserBlazor.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

#ENTRYPOINT ["dotnet", "UserBlazor.dll"]
ENTRYPOINT [ "dotnet", "UserBlazor.dll", "--urls", "http://0.0.0.0:9001"]