apiVersion: v1
kind: Service
metadata:
  name: userblazor
spec:
  selector:
    app: userblazor
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 9001
    targetPort: 9001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userblazor
spec:
  selector:
    matchLabels:
      app: userblazor
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: userblazor
        tier: frontend
        track: stable
    spec:
      containers:
      - name: userblazor
        image: userblazor
        imagePullPolicy: Never
        ports:
        - containerPort: 9001